version: dev-{build}
clone_folder: C:\projects\guzaba2

environment:
    matrix:
        - php_ver: 7.2
        
cache:
    - '%APPDATA%\Composer'
    - '%LOCALAPPDATA%\Composer'
    - C:\tools\php -> .appveyor.yml
    - C:\tools\composer.phar -> .appveyor.yml
    
init:
    - SET PATH=C:\tools\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1 # This var is connected to PHP install cache
    
install:
    - IF NOT EXIST C:\tools\php (SET PHP=0)
    - IF %PHP%==0 (choco install --yes --allow-empty-checksums php --version %php_ver% --params '/InstallDir:C:\tools\php')
    - cd C:\tools\php
    - copy php.ini-production php.ini
    - IF %PHP%==0 (appveyor DownloadFile https://getcomposer.org/composer.phar)
    - cd c:\projects\guzaba2
    - appveyor-retry composer install --no-progress --profile
    - appveyor-retry composer require friendsofphp/php-cs-fixer:~2.2 --no-progress --profile
    
test_script:
    - cd C:\projects\guzaba2
    - set PHP_CS_FIXER_FUTURE_MODE=1
    - php php-cs-fixer --diff --dry-run -v fix
