build: false
version: dev-{build}
clone_folder: C:\projects\guzaba2

environment:
    matrix:
        - php_ver: 7.2
        
cache:
    - '%LOCALAPPDATA%\Composer\files -> composer.lock'
    # Cache chocolatey packages
    - C:\ProgramData\chocolatey\bin -> .appveyor.yml
    - C:\ProgramData\chocolatey\lib -> .appveyor.yml
    # Cache php install
    - C:\tools\php -> .appveyor.yml
    
init:
    - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1 # This var is connected to PHP install cache
    
install:
    #php
    - IF NOT EXIST C:\tools\php (SET PHP=0)
    - ps: appveyor-retry cinst --params '""/InstallDir:C:\tools\php""' --ignore-checksums -y php --version %php_ver%
    - cd C:\tools\php   
    - copy php.ini-production php.ini
    - IF %PHP%==0 echo extension_dir=ext >> php.ini
    - IF %PHP%==0 echo extension=php_openssl.dll >> php.ini 
    #composer
    - IF %PHP%==0 echo @php %%~dp0composer.phar %%* > composer.bat
    - IF %PHP%==0 appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
    #install
    - cd c:\projects\guzaba2
    - appveyor-retry composer install --no-progress --profile
    - appveyor-retry composer require friendsofphp/php-cs-fixer:~2.2 --no-progress --profile
    
test_script:
    - cd C:\projects\guzaba2
    - set PHP_CS_FIXER_FUTURE_MODE=1
    - php php-cs-fixer --diff --dry-run -v fix
